### ISSUE TITLE
Replace  CLOB datatype with JSON datatype

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig-privacy#45]
MySQL 5.7 introduced a [JSON datatype](https://dev.mysql.com/doc/refman/5.7/en/json.html).  We should use the JSON datatype instead of a CLOB in the De-Identification service so that we can perform queries over JSON data.

### Acceptance Criteria
* All CLOB datatypes that store JSON data must be replaced with the JSON datatype.

**Comment by gmcfall** [comment]
@ElakiyaUdhayanan  if you are blocked or have no tasks for the Australia project, please work on this issue.

**Comment by SriramMani1** [comment]
Data Type has been changed to Json
